dist: trusty
sudo: required
language: node_js

node_js:
  - "8"
os:
  - linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm run build-lib
  - npm run test-lib-coverage
after_success:
  - npm run report-coverage
before_deploy:
  - cd dist
deploy:
  provider: npm
  email: kevin.kreuzer90@icloud.com
  api_key: ${NPM_KEY}
  on:
    tags: true
  skip_cleanup: true
